---
title: "methods comparaison"
author: "Jordan Benrezkallah"
date: "4/18/2022"
output: pdf_document
---

```{r setup, include=FALSE}
library("readxl")
library(dplyr)
#library(ggpubr)
library(tidyverse)
library(knitr)
library(ggplot2)
library(ggpubr)
library(ggthemes)

```

```{r site}
df <- as.data.frame(read_excel("DATA R/method_R.xlsx",sheet = "R"))
df$pop <- as.numeric(df$pop)
df$low <- as.numeric(df$low)
df$up <- as.numeric(df$up)

ggplot(df, aes(fill=method, y=pop, x=site)) + 
  geom_bar(position="dodge", stat="identity", colour="black", size = 0.3) +
  geom_errorbar(aes(ymin=low, ymax=up), width=.2,
                 position=position_dodge(.9)) + 
  geom_text(aes(label=pop, y= 450), position=position_dodge(width=0.9), vjust=-0.25,
            fontface = "bold", size = 6) +
  labs(x = "Study site", y = "Population estimate",fill = "Method",fontface = "bold") + 
  scale_fill_brewer(palette="Set1") +
  theme(axis.title.x = element_text(face="bold", size = 20), # Study site
        axis.title.y = element_text(face="bold", size = 20), # Population estimate
        axis.text.x = element_text(face="bold", color= "black", size=18), # A C D
        axis.text.y = element_text(face="bold", color= "black", size=18), # 0 100 200 300 400
        panel.grid.major = element_blank(),panel.grid.minor = element_blank(),
        panel.background = element_rect(fill='white', colour='black'),
        legend.title = element_text(size=20, face="bold"), # le mot "Method" dans la légende
        legend.text = element_text(size=20, face="bold"), # les methods dans la légende
        legend.position="bottom") 


```
```{export to pdf}

ggsave(filename = "D:/OneDrive - UMONS/UMONS/MA2/ERASMUS CHYPRE/Internship report/img/site_compared.pdf", device = cairo_pdf)

```

```{export to png}

ggsave(filename = "D:/OneDrive - UMONS/UMONS/MA2/ERASMUS CHYPRE/Internship report/img/site_compared.png", device = "png", width = 32, height = 17, units = "cm" )

```

```{r barplot}
df <- as.data.frame(read_excel("DATA/method_R.xlsx",sheet = "R"))
df$pop <- as.numeric(df$pop)

barplot(height = df$pop, names= df$site, main=NULL, ylab = "(CI 95%)", cex.lab = 1.5, cex.main = 1.4, beside=TRUE, col=c("darkblue","red"))


#ggsave(filename = "regression_A.pdf", device = cairo_pdf)
```